import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { ResponsiveContainer, RadialBarChart, RadialBar, PolarAngleAxis, } from "recharts";
import { getCache } from "../api";
import { StatCard } from "../components/StatCard";
function Spinner() {
    return (_jsx("div", { className: "flex items-center justify-center h-64", children: _jsx("div", { className: "w-8 h-8 border-4 border-indigo-100 border-t-indigo-500 rounded-full animate-spin" }) }));
}
function RateGauge({ value, color, label }) {
    const pct = Math.min(value * 100, 100);
    return (_jsxs("div", { className: "flex flex-col items-center", children: [_jsx(ResponsiveContainer, { width: 160, height: 160, children: _jsxs(RadialBarChart, { cx: "50%", cy: "50%", innerRadius: "65%", outerRadius: "90%", startAngle: 90, endAngle: -270, data: [{ value: pct, fill: color }], children: [_jsx(PolarAngleAxis, { type: "number", domain: [0, 100], tick: false }), _jsx(RadialBar, { dataKey: "value", cornerRadius: 8, background: { fill: "#f3f4f6" } })] }) }), _jsxs("div", { className: "text-2xl font-bold text-gray-900 -mt-16", children: [pct.toFixed(1), "%"] }), _jsx("div", { className: "text-xs text-gray-500 mt-1", children: label })] }));
}
export function Cache() {
    const [data, setData] = useState(null);
    useEffect(() => {
        getCache(7).then(setData);
    }, []);
    if (!data)
        return _jsx(Spinner, {});
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-xl font-bold text-gray-900", children: "Cache Analysis" }), _jsx("p", { className: "text-sm text-gray-500 mt-0.5", children: "Duplicate and prefix overlap rates \u00B7 7-day window" })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsx(StatCard, { title: "Duplicate Prompt Rate", value: `${(data.duplicate_prompt_rate * 100).toFixed(2)}%`, hint: "Exact-match repeated prompts", accent: data.duplicate_prompt_rate > 0.1 ? "amber" : "default" }), _jsx(StatCard, { title: "Prefix Overlap Rate", value: `${(data.prefix_overlap_rate * 100).toFixed(2)}%`, hint: "Shared 200-char prefix", accent: data.prefix_overlap_rate > 0.1 ? "amber" : "default" })] }), _jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-sm p-6", children: [_jsx("h3", { className: "text-sm font-semibold text-gray-700 mb-6", children: "Cache Opportunity Gauges" }), _jsxs("div", { className: "flex gap-12 justify-center flex-wrap", children: [_jsx(RateGauge, { value: data.duplicate_prompt_rate, color: "#6366f1", label: "Duplicate Prompts" }), _jsx(RateGauge, { value: data.prefix_overlap_rate, color: "#10b981", label: "Prefix Overlap" })] }), _jsx("p", { className: "text-xs text-gray-400 text-center mt-4", children: "Higher values mean more potential cache savings. Identical requests are already deduplicated by the gateway's LRU cache." })] }), _jsxs("div", { className: "bg-white rounded-xl border border-gray-100 shadow-sm p-6", children: [_jsx("h3", { className: "text-sm font-semibold text-gray-700 mb-4", children: "Top Duplicate Prompts" }), data.top_duplicates.length === 0 ? (_jsx("p", { className: "text-sm text-gray-400", children: "No duplicates detected in the current window." })) : (_jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-gray-100", children: [_jsx("th", { className: "text-left pb-2 text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "Prompt Hash" }), _jsx("th", { className: "text-right pb-2 text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "Occurrences" })] }) }), _jsx("tbody", { children: data.top_duplicates.map((r, i) => (_jsxs("tr", { className: i % 2 === 0 ? "bg-gray-50/50" : "", children: [_jsxs("td", { className: "py-2.5 font-mono text-xs text-gray-600", children: [r.prompt_hash.slice(0, 24), "\u2026"] }), _jsx("td", { className: "py-2.5 text-right", children: _jsxs("span", { className: "inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-700", children: [r.count, "\u00D7"] }) })] }, r.prompt_hash))) })] }))] })] }));
}
